name: deploy

on:
  push:
    branches:
      - main  # 或者是你的源代码分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Hugo site
        run: hugo -F --cleanDestinationDir

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        # uses:  peaceiris/actions-hugo@v2
        with:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}  # 你的个人访问令牌
          EXTERNAL_REPOSITORY: yangwentingnku/yangwentingnku.github.io  # 你的GitHub Pages仓库
          PUBLISH_BRANCH: gh-pages  # 或者是你的GitHub Pages分支
          PUBLISH_DIR: public
          commit_message: ${{ github.event.head_commit.message }}
